name: airbyte_utils
version: '1.0'
config-version: 2

profile: normalize

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
packages-install-path: '../dbt_packages'

target-path: "target"  # directory which will store compiled SQL files
log-path: ../logs

clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: incremental
        +on_schema_change: sync_all_columns
      airbyte_tables:
        +tags: normalized_tables
        +materialized: table
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
dispatch:
- macro_namespace: dbt_utils
  search_order:
  - airbyte_utils
  - dbt_utils
vars:
  json_column: _airbyte_data
  models_to_source:
    deals_ab1: public._airbyte_raw_deals
    deals_ab2: public._airbyte_raw_deals
    deals_ab3: public._airbyte_raw_deals
    deals: public._airbyte_raw_deals
    deals_properties_ab1: public._airbyte_raw_deals
    deals_properties_ab2: public._airbyte_raw_deals
    deals_properties_ab3: public._airbyte_raw_deals
    deals_properties: public._airbyte_raw_deals
